In [ ]:
'''
Projeto ETL SQL to Cloud Storage

Criar uma instância com MySQL no Google Cloud SQL
Criar um banco de dados com o nome loja nesta instância
Popular esse banco de dados com os dados do arquivo deste link:
https://colab.research.google.com/drive/18--jmuhLkQbKsJ5jJdI8W6y0ManYtr0r?usp=sharing

Criar um colab para fazer a conexão com este banco loja:
trazer todas as informações de todas as tabela desse banco para o ambiente Python/Pandas
Enviar todas as tabelas desse banco para um bucket no google cloud storage chamado loja, dentro de uma pasta chamada tabelas;
Conceder acesso ao projeto no IAM para douglas.ribeiro@soulcode.com
Entregar o link do colab no google Classroom

'''

In [ ]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (6.0 kB)
Downloading mysql_connector_python-9.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (34.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 15.0 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.1.0

In [ ]:
import pandas as pd
import mysql.connector

In [ ]:
usuario = 'root'
password = ''
database = 'Loja'
host = '34.44.38.90'

In [ ]:
!curl ipecho.net/plain

34.19.97.253

In [ ]:
connection = mysql.connector.connect(
    host = host,
    user = usuario,
    password=password,
    database=database,
    ) # linhas para criar a conexão com o banco de dados

cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = ''' SELECT * FROM Cliente;
''' #Query ou consulta desejada
cursor.execute(query) #execução da consulta
result = cursor.fetchall() #armazenando os resultados na variavel results
cliente = pd.DataFrame(result,columns=cursor.column_names) #Converte a variavel result em um df pandas nomeado de tabelas
display(cliente)
cursor.close()
connection.close()

    id_cliente         nome endereco
0            1      Douglas       SP
1            2      Daniela       SP
2            3        Ester       MG
3            4        Maria       BA
4            5      Douglas       PE
5            6     Raimundo       CE
6            7     Jucimara       GO
7            8      Marlene       AC
8            9      Douglas       MA
9           10      Daniela       PI
10          11        Pedro       PB
11          12      Joaquim       RS
12          13        Julio       TO
13          14        Carla       DF
14          15       Bianca       PA
15          16       Sandra       SP
16          17        Celso       SP
17          18      Silvana       BA
18          19  Prof Raquel       BA
19          20        Pedro       SP
20          21        Erick       BA
21          22       Denise       DF
22          23        Diana       SP
23          24       Dagmar       DF
24          25    Deiverson       SP

In [ ]:
from google.colab import auth
auth.authenticate_user()
project_id = 'fifth-brook-440013-a0'
!gcloud config set project {project_id}
from google.cloud import storage
storage = storage.Client()
bucket_name = 'lojadanny'
bucket = storage.bucket(bucket_name)
itempedido.to_csv('itempedido.csv',index=False)
#from google.cloud import storage
destination_blob_name = 'tabelas/tabela_itempedido.csv'
source_file_name = 'itempedido.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
from google.colab import auth
auth.authenticate_user()
project_id = 'fifth-brook-440013-a0'
!gcloud config set project {project_id}
from google.cloud import storage
storage = storage.Client()
bucket_name = 'lojadanny'
bucket = storage.bucket(bucket_name)
categoria.to_csv('categoria.csv',index=False)
#from google.cloud import storage
destination_blob_name = 'tabelas/tabela_categoria.csv'
source_file_name = 'categoria.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
from google.colab import auth
auth.authenticate_user()
project_id = 'fifth-brook-440013-a0'
!gcloud config set project {project_id}
from google.cloud import storage
storage = storage.Client()
bucket_name = 'lojadanny'
bucket = storage.bucket(bucket_name)
produtocategoria.to_csv('produtocategoria.csv',index=False)
#from google.cloud import storage
destination_blob_name = 'tabelas/tabela_produtocategoria.csv'
source_file_name = 'produtocategoria.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].

In [ ]:
from google.colab import auth
auth.authenticate_user()
project_id = 'fifth-brook-440013-a0'
!gcloud config set project {project_id}
from google.cloud import storage
storage = storage.Client()
bucket_name = 'lojadanny'
bucket = storage.bucket(bucket_name)
cliente.to_csv('cliente.csv',index=False)
#from google.cloud import storage
destination_blob_name = 'tabelas/tabela_clientes.csv'
source_file_name = 'cliente.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

Updated property [core/project].